//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tweeta.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tweeta.Resources.Strings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tweeta.
        /// </summary>
        public static string ApplicationNameLower {
            get {
                return ResourceManager.GetString("ApplicationNameLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweeta.
        /// </summary>
        public static string ApplicationNameSentance {
            get {
                return ResourceManager.GetString("ApplicationNameSentance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWEETA.
        /// </summary>
        public static string ApplicationNameUpper {
            get {
                return ResourceManager.GetString("ApplicationNameUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string PanoramaMe {
            get {
                return ResourceManager.GetString("PanoramaMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string PanoramaSearch {
            get {
                return ResourceManager.GetString("PanoramaSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeline.
        /// </summary>
        public static string PanoramaTimeline {
            get {
                return ResourceManager.GetString("PanoramaTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trending.
        /// </summary>
        public static string PanoramaTrending {
            get {
                return ResourceManager.GetString("PanoramaTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileViewProfile {
            get {
                return ResourceManager.GetString("ProfileViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tweets.
        /// </summary>
        public static string ProfileViewTweets {
            get {
                return ResourceManager.GetString("ProfileViewTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter username.
        /// </summary>
        public static string TwitterUsername {
            get {
                return ResourceManager.GetString("TwitterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
